# Generated by Django 5.2.4 on 2025-08-05 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yogiyo', '0002_category_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='num',
        ),
    ]
